// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtqcJCLfaERhOAP6X_44mbaLeRHj_6P7I',
    appId: '1:275013377125:web:68b389139fe01051793a8c',
    messagingSenderId: '275013377125',
    projectId: 'fast-pms-75d98',
    authDomain: 'fast-pms-75d98.firebaseapp.com',
    storageBucket: 'fast-pms-75d98.appspot.com',
    measurementId: 'G-PPPP007E94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRoBwxYHB2fp_exWfJeb3O_Q3l-4rvkw',
    appId: '1:275013377125:android:e8bede7406fa0071793a8c',
    messagingSenderId: '275013377125',
    projectId: 'fast-pms-75d98',
    storageBucket: 'fast-pms-75d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl5pFESfWSA8ZLubkMvO98ISiv2qb4Lwk',
    appId: '1:275013377125:ios:74107ebf3708b6cd793a8c',
    messagingSenderId: '275013377125',
    projectId: 'fast-pms-75d98',
    storageBucket: 'fast-pms-75d98.appspot.com',
    iosClientId: '275013377125-u48gt0d6i7e7q4ovl86gpqfljp337ecu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastPmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl5pFESfWSA8ZLubkMvO98ISiv2qb4Lwk',
    appId: '1:275013377125:ios:74107ebf3708b6cd793a8c',
    messagingSenderId: '275013377125',
    projectId: 'fast-pms-75d98',
    storageBucket: 'fast-pms-75d98.appspot.com',
    iosClientId: '275013377125-u48gt0d6i7e7q4ovl86gpqfljp337ecu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastPmsApp',
  );
}
